source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'PenzaAuto' do
  use_frameworks!
  
  pod 'Alamofire', '~> 4.0'
  pod 'SnapKit', '~> 4.0.0'
end

target 'PenzaAutoTests' do
  use_frameworks!
  
  pod 'Alamofire', '~> 4.0'
  pod 'Mockit', '1.5.0'
end
